<?php
/**
 * Roundcube Webmail — Filemanager Plugin
 *
 * File    : /plugins/filemanager/localization/id_ID.inc
 * Path    : /var/www/roundcube/plugins/filemanager/localization/id_ID.inc
 *
 * Label terjemahan bahasa Indonesia.
 * Dimuat otomatis oleh $this->add_texts('localization/', false)
 * dan diakses via $this->gettext('filemanager.navtitle').
 *
 * @author     ArisCiwek
 * @license    GNU AGPL v3 or later
 * @package    Filemanager
 * @subpackage Localization
 */

$labels = [];

$labels['navtitle'] = 'Berkas';
$labels['myfiles']  = 'Berkas Saya';
$labels['shared']   = 'Dibagikan';
$labels['trash']    = 'Sampah';